Does going to university in a different country affect your mental health? A Japanese international university surveyed its students in 2018 and published a study the following year that was approved by several ethical and regulatory boards.

The study found that international students have a higher risk of mental health difficulties than the general population. Explore the `students` data using PostgreSQL to find out if this is true and see if the length of stay is a contributing factor.

Here is a data description of the columns you may find helpful.

| Field Name    | Description                                      | 
| ------------- | ------------------------------------------------ |
| inter_dom     | Types of students                                |
| japanese_cate | Japanese language proficiency                    | 
| english_cate  | English language proficiency                     |
| academic      | Current academic level                           | 
| age           | Current age of student                           |
| stay          | Current length of stay in years                  |
| todep         | Total score of depression (PHQ-9 test)           |
| tosc          | Total score of social connectedness (SCS test)   |
| toas          | Total score of Acculturative Stress (ASISS test) |

In [2]:
SELECT *
FROM students
LIMIT 5;

  inter_dom region  gender academic  ...  religion_bi  alone_bi  others_bi internet_bi
0     Inter    SEA    Male     Grad  ...           No        No         No          No
1     Inter    SEA    Male     Grad  ...           No        No         No          No
2     Inter    SEA    Male     Grad  ...           No        No         No          No
3     Inter     EA  Female     Grad  ...           No        No         No          No
4     Inter     EA  Female     Grad  ...          Yes        No         No          No

[5 rows x 50 columns]

In [5]:
# Checking summary statistics for different groups
SELECT
    inter_dom
    ,gender
    ,region
    ,COUNT(*) AS count_students
    ,MIN(todep) AS min_todep
    ,MAX(todep) AS max_todep
    ,AVG(todep) AS avg_todep

FROM students

GROUP BY 
    inter_dom
    ,gender
    ,region

ORDER BY
    inter_dom DESC
    ,gender DESC
    ,region DESC;

   inter_dom  gender  region  count_students  min_todep  max_todep  avg_todep
0      Inter    Male     SEA              32        0.0       24.0   7.437500
1      Inter    Male      SA              13        1.0       13.0   7.153846
2      Inter    Male  Others               3        3.0       13.0   8.000000
3      Inter    Male     JAP               1        2.0        2.0   2.000000
4      Inter    Male      EA              24        0.0       21.0   7.875000
5      Inter  Female     SEA              90        0.0       22.0   8.477778
6      Inter  Female      SA               5        1.0       19.0   6.800000
7      Inter  Female  Others               8        0.0       19.0   6.750000
8      Inter  Female     JAP               1       13.0       13.0  13.000000
9      Inter  Female      EA              24        2.0       25.0   8.625000
10       Dom    Male     JAP              25        0.0       23.0   8.800000
11       Dom  Female     JAP              42        0.0       21.0   8.500000
12                                        18        NaN        NaN        NaN

In [10]:
# Lenght of stay, impacting scores of inter students?
SELECT
    stay
    ,ROUND(AVG(todep),2) AS average_phq
    ,ROUND(AVG(tosc),2) AS average_scs
    ,ROUND(AVG(toas),2) AS average_as

FROM students

WHERE
    inter_dom = 'Inter'
    AND stay IS NOT NULL

GROUP BY
    stay
    
ORDER BY
    stay DESC;

   stay  average_phq  average_scs  average_as
0    10        13.00        32.00       50.00
1     8        10.00        44.00       65.00
2     7         4.00        48.00       45.00
3     6         6.00        38.00       58.67
4     5         0.00        34.00       91.00
5     4         8.57        33.93       87.71
6     3         9.09        37.13       78.00
7     2         8.28        37.08       77.67
8     1         7.48        38.11       72.80